services:
  # PostgreSQL database service
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user # database username
      POSTGRES_PASSWORD: password # database password
      POSTGRES_DB: todo_db # database name
    ports:
      - "5432:5432" # PostgreSQL default port
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # pgAdmin dashboard for managing PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # admin login email
      PGADMIN_DEFAULT_PASSWORD: admin123 # admin login password
    ports:
      - "5050:80" # pgAdmin web UI
    depends_on:
      - db

volumes:
  postgres_data: # persistent storage for PostgreSQL data
